export default {
    "user-shared-coupon": "Пользователь поделился купоном",
    "user-shared-organization": "Пользователь поделился организацией",
    "adding-coupon-user": "Добавление купона организации к пользователю",
    "coupon-invoice-creation": "Создание счета по покупке купона",
    "purchase-user-create": "Пользователь создал покупку",
    "purchase-user-pay": "Создание запроса на оплату покупки",
    "purchase-user-pay-cash": "Оплата покупки за наличные",
    "start-app": "Заход на главный экран приложения",
    "user-created-withdrawal-request": "Пользователь перешел на форму вывода средств",
    "user-shared-cutaway": "Пользователь поделился визиткой",
    "user-shared-purchase": "Пользователь поделился оплаченным купоном",
    "user-subscribe-organization": "Пользователь подписался на организацию",
    "user-subscribed-invitation-cutaway": "Пользователь подписался на визитную карточки по приглашению",
    "user-unsubscribe-organization": "Пользователь отписался от организации",
    "user-open-organization": "Пользователь открыл страницу организации",
    "user-open-coupon": "Пользователь открыл страницу купон",
    "user-send-tips": "Пользователь отправил чаевые",
    "user-authorization": "Авторизация пользователя AdWise Cards",
    "user-registration": "Регистрация пользователя AdWise Cards",
    "user-registration-parent": "Регистрация пользователя  приглашению AdWise Cards",
    "user-password-reset": "Сброс пароля пользователя AdWise Cards",
    "user-open-page-settings": "Пользователь открыл раздел 'Настройки'",

    // Кассир
    "error-from-business": "Ошибка из приложения AdWise Cashier",
    "scan-purchase": "Сканирование покупки",
    "open-scan-purchase": "Запуск сканирования покупки",
    "completion-order": "Завершение заказа",
    "confirmation-cash-payment": "Подтверждение наличной оплаты",
    "user-card-binding": "Привязка карты пользователя",
    "create-purchase-from-app": "Создание покупки из приложения",
}
