export default {
    purchase: 'Базовый доход с продажи',
    packet: 'Продажа лицензии',
    ref: 'Бонус с покупки реферала',
    offer: 'Кэшбэк',
    managerPercent: 'Процент менеджера',
    refBackToOrganization: 'Нереализованные баллы',
    adwise: 'Процент эдвайс с покупки',
    usedPoints: 'Использование баллов',
    deposit: 'Внесение депозита',
    depositBack: 'Вывод депозита',
    withdrawal: 'Вывод',
    payment: 'Оплата',
    packetRef: 'Награда реф.сети (лицензия)',
    correct: 'Корректировка баланса',
    correctBonus: 'Корректировка баланса (бонусы)',
    correctCashback: 'Корректировка баланса (кэшбэк)',
    cashPurchase: 'Покупка из приложения за наличные',
    marketingDeposit: 'Списание с депозита за маркетинг',
    tips: 'Чаевые',
    paymentGateway: "Комиссия платежного шлюза"
};
