import * as ImagePicker from "expo-image-picker";

export default {
    "startScreenButtonRegistration": "start_screen.buttons.registration",
    "startScreenButtonAuthorization": "start_screen.buttons.authorization",
    "startScreenButtonPrivacyPolicy": "start_screen.buttons.privacy_policy",
    "startScreenButtonTermsUse": "start_screen.buttons.terms_use",
    "startScreenButtonCancel": "start_screen.buttons.cancel",
    "startScreenPoliticalStart": "start_screen.political.start",
    "startScreenPoliticalPrivacyPolicy": "start_screen.political.privacyPolicy",
    "startScreenPoliticalTermsUse": "start_screen.political.termsUse",
    "startScreenPoliticalEnd": "start_screen.political.end",


    "registrationHeaderWelcome": "registration.header.welcome",
    "registrationHeaderPhoneNumber": "registration.header.phone_number",
    "registrationHeaderEnterCodeSms": "registration.header.enter_code_sms",
    "registrationStageOnePleaseRegister": "registration.stage_one.please_register",
    "registrationStageOneAlreadyRegistered": "registration.stage_one.already_registered",
    "registrationStageTwoSendConfirmationCode": "registration.stage_two.send_confirmation_code",
    "registrationStageThreeSentTo": "registration.stage_three.sent_to",
    "registrationStageThreeCodeValidFor": "registration.stage_three.code_valid_for",
    "registrationStageThreeCodeTimedRequestNew": "registration.stage_three.code_timed_request_new",
    "registrationStageThreeDidntReceiveCode": "registration.stage_three.didnt_receive_code",
    "registrationFormsPhoneNumber": "registration.forms.phone_number",
    "registrationButtonsByPhone": "registration.buttons.by_phone",
    "registrationButtonsLoginHere": "registration.buttons.login_here",
    "registrationButtonsProceed": "registration.buttons.proceed",
    "registrationButtonsResend": "registration.buttons.resend",
    "registrationErrorsNumberEnteredIncorrectly": "registration.errors.number_entered_incorrectly",
    "registrationErrorsNumberRegisteredSystem": "registration.errors.number_registered_system",
    "registrationLoadingsChecksPhone": "registration.loadings.checks_phone",
    "registrationLoadingsSendCodePhoneNumber": "registration.loadings.send_code_phone_number",
    "registrationModalFilingTitle": "registration.modal_filing.title",
    "registrationModalFilingMessage": "registration.modal_filing.message",
    "registrationModalFilingButtonSkip": "registration.modal_filing.button_skip",
    "registrationModalFilingButtonGo": "registration.modal_filing.button_go",


    "authorizationHeaderEntry": "authorization.header.entry",
    "authorizationErrorsWrongLoginPassword": "authorization.errors.wrong_login_password",
    "authorizationFormsPhone": "authorization.forms.phone",
    "authorizationFormsPassword": "authorization.forms.password",
    "authorizationButtonsForgotPassword": "authorization.buttons.forgot_password",
    "authorizationButtonsEntry": "authorization.buttons.entry",

    "dashboardBusinessCardsPersonal": "dashboard.businessCards.personal",
    "dashboardBusinessCardsWorking": "dashboard.businessCards.working",
    "dashboardBusinessCardsInstalledActiveBusinessCard": "dashboard.businessCards.installed_active_business_card",
    "dashboardRecommendationTitle": "dashboard.recommendation.title",
    "dashboardRecommendationEmpty": "dashboard.recommendation.empty",
    "dashboardConnectionsTitle": "dashboard.connections.title",
    "dashboardConnectionsEmpty": "dashboard.connections.empty",
    "dashboardQrCodeTitle": "dashboard.qr_code.title",
    "dashboardNotificationSubscriptionMessage": "dashboard.notification.subscription.message",
    "dashboardNotificationContactRequestTitle": "dashboard.notification.contact_request.title",
    "dashboardNotificationContactRequestMessage": "dashboard.notification.contact_request.message",
    "dashboardNotificationPurchaseAddedTitle": "dashboard.notification.purchase_added.title",
    "dashboardNotificationPurchaseAddedMessage": "dashboard.notification.purchase_added.message",
    "dashboardNotificationPurchaseConfirmedTitle": "dashboard.notification.purchase_confirmed.title",
    "dashboardNotificationPurchaseConfirmedMessage": "dashboard.notification.purchase_confirmed.message",
    "dashboardErrorsOrganizationEmptyTitle": "dashboard.errors.organization_empty.title",
    "dashboardErrorsOrganizationEmptyMessage": "dashboard.errors.organization_empty.message",
    "dashboardErrorsCouponEmptyTitle": "dashboard.errors.coupon_empty.title",
    "dashboardErrorsCouponEmptyMessage": "dashboard.errors.coupon_empty.message",

    "myCouponsTitle": "my_coupons.title",
    "myCouponsSectionsFixedTitle": "my_coupons.sections.fixed.title",

    "couponTermsAction": "coupon.terms_action",
    "couponCashbackInformation": "coupon.cashback_information",

    "paymentsTitle": "payments.title",
    "paymentsTitleArchive": "payments.title_archive",
    "paymentsTabsCurrent": "payments.tabs.current",
    "paymentsTabsHistory": "payments.tabs.history",
    "paymentsNotificationsReviewedSuccessfully": "payments.notifications.reviewed_successfully",
    "paymentsNotificationsReviewedError": "payments.notifications.reviewed_error",
    "paymentsNotificationsTipsError": "payments.notifications.tips_error",
    "paymentsTotalCountPurchaseTotalCountPurchase": "payments.total_count_purchase",
    "paymentsSuccessSendPurchase": "payments.success_send_purchase",
    "paymentsSuccessCashPurchase": "payments.success_cash_payment",

    "purchaseButtonsToArchive": "purchase.buttons.to_archive",
    "purchaseOrder": "purchase.order",
    "purchaseTextLoading": "purchase.text_loading",
    "purchasePurchaseData": "purchase.purchase_data",
    "purchasePurchasePayment": "purchase.purchase_payment",
    "purchaseOrderNotFound": "purchase.order_not_found",
    "purchaseCreatedBy": "purchase.created_by",
    "purchasePaidBy": "purchase.paid_by",
    "purchaseCompletedBy": "purchase.completed_by",
    "purchasePurchaseAmount": "purchase.purchase_amount",
    "purchaseCashbackAmount": "purchase.cashback_amount",
    "purchaseOrderNumber": "purchase.order_number",
    "purchaseSeller": "purchase.seller",
    "purchasePaidPoints": "purchase.paid_points",
    "purchaseBonusesMyBonus": "purchase.bonuses.my_bonus",
    "purchaseBonusesPlaceholder": "purchase.bonuses.placeholder",
    "purchaseBonusesButtonMax": "purchase.bonuses.button_max",
    "purchaseBonusesHint": "purchase.bonuses.hint",
    "purchaseCommentTitle": "purchase.comment.title",
    "purchaseCommentPlaceholder": "purchase.comment.placeholder",
    "purchaseControlsPaymentAmount": "purchase.controls.payment_amount",
    "purchaseControlsButtonOnline": "purchase.controls.button_online",
    "purchaseControlsButtonCash": "purchase.controls.button_cash",
    "purchaseControlsErrorCash": "purchase.controls.error_cash",
    "purchaseEvaluationTitle": "purchase.evaluation.title",
    "purchaseEvaluationYourFeedback": "purchase.evaluation.your_feedback",
    "purchaseEvaluationYourFeedbackPlaceholder": "purchase.evaluation.your_feedback_placeholder",
    "purchaseNotification": "purchase.notification",
    "purchaseCashierTitle": "purchase.cashier_title",
    "purchaseSendErrorPurchase": "purchase.send_error_purchase",
    "purchaseSuccessCommentSend": "purchase.success_comment_send",

    "financialSectionHeaderSwitchFinancialSection": "financial_section.header_switch.financial_section",
    "financialSectionHeaderSwitchReferralProgram": "financial_section.header_switch.referral_program",
    "financialSectionMyFinancesTitle": "financial_section.my_finances.title",
    "financialSectionMyFinancesTimeUpdatedAt": "financial_section.my_finances.time_updated_at",
    "financialSectionMyFinancesYourBalance": "financial_section.my_finances.your_balance",
    "financialSectionMyFinancesToEnrollment": "financial_section.my_finances.to_enrollment",
    "financialSectionMyFinancesButtonWithdrawalFunds": "financial_section.my_finances.button_withdrawal_funds",
    "financialSectionMyFinancesChecks": "financial_section.my_finances.checks",
    "financialSectionMyFinancesPurchaseAmount": "financial_section.my_finances.purchase_amount",
    "financialSectionMyFinancesRewards": "financial_section.my_finances.rewards",
    "financialSectionMyFinancesUsedPointsSum": "financial_section.my_finances.used_points_sum",
    "financialSectionMyFinancesWithdrawalSum": "financial_section.my_finances.withdrawal_sum",
    "financialSectionHistoryTitle": "financial_section.history.title",
    "financialSectionHistoryRowMarketing": "financial_section.history.row_marketing",
    "financialSectionHistoryRowPurchase": "financial_section.history.row_purchase",
    "financialSectionHistoryRowWithdrawal": "financial_section.history.row_withdrawal",
    "financialSectionHistoryRowUsePoints": "financial_section.history.row_use_points",

    "referralProgramFounderTitle": "referral_program.founder.title",
    "referralProgramFounderNotData": "referral_program.founder.not_data",
    "referralProgramFounderFounderCardTotalPercentage": "referral_program.founder.founder_card.total_percentage",

    "accountUserCopyCode": "account.user.copy_code",
    "accountUserYourCode": "account.user.your_code",
    "accountMenuFeedback": "account.menu.feedback",
    "accountMenuContacts": "account.menu.contacts",
    "accountMenuAboutApp": "account.menu.about_app",
    "accountMenuLegalInformationHome": "account.menu.legal_information_home",
    "accountMenuSettings": "account.menu.settings",
    "accountMenuMyPaymentsArchive": "account.menu.my_payments_archive",
    "accountMenuCouponsDisabled": "account.menu.coupons_disabled",
    "accountMenuExit": "account.menu.exit",
    "accountInvitationTitle": "account.invitation.title",
    "accountInvitationDescription": "account.invitation.description",
    "accountApplicationDescription": "account.application.description",
    "accountApplicationButton": "account.application.button",

    "profileHeader": "profile.header",
    "profileHeaderEdit": "profile.header_edit",
    "profileName": "profile.name",
    "profileSurname": "profile.surname",
    "profileGender": "profile.gender",
    "profileDateBirth": "profile.date_birth",
    "profilePhone": "profile.phone",
    "profileProvideEmail": "profile.provide_email",
    "profileProvidePhoneNumber": "profile.provide_phone_number",
    "profileEdit": "profile.edit",
    "profileSendEdit": "profile.send_edit",
    "profileChange": "profile.change",
    "profileUploadImage": "profile.upload_image",
    "profileHelpEditMessage": "profile.help_edit_message",
    "profileUpdatingContacts": "profile.updating_contacts",
    "profileDataChangedSuccessfully": "profile.data_changed_successfully",

    "purchaseStatusPaid": "purchaseStatus.paid",
    "purchaseStatusCanceled": "purchaseStatus.canceled",
    "purchaseStatusNotPaid": "purchaseStatus.not_paid",
    "purchaseStatusDuring": "purchaseStatus.during",
    "purchaseStatusCompleted": "purchaseStatus.completed",

    "commonSearch": "common.search",
    "commonScheduler": "common.scheduler",
    "commonPleaseSelect": "common.please_select",
    "commonDone": "common.done",
    "commonLoadingProgress": "common.loading_progress",
    "commonScan": "common.scan",
    "commonSend": "common.send",
    "commonShare": "common.share",
    "commonOrganizations": "common.organizations",
    "commonHide": "common.hide",
    "commonUnpin": "common.unpin",
    "commonAnchor": "common.anchor",
    "commonCollapse": "common.collapse",
    "commonExpandDescription": "common.expand_description",
    "commonClear": "common.clear",
    "commonSubscribe": "common.subscribe",
    "commonCashback": "common.cashback",
    "commonPay": "common.pay",
    "commonReceive": "common.receive",
    "commonLeaveTip": "common.leave_tip",
    "commonLoadingMessage": "common.loading_message",
    "commonContactSupport": "common.contact_support",
    "commonNotData": "common.not_data",
    "commonCurrentCityEmpty": "common.current_city_empty",
    "commonSystemNotification": "common.system_notification",
    "commonOrganizationDisabled": "common.organization_disabled",
    "commonCouponDisabled": "common.coupon_disabled",
    "commonUnsubscribe": "common.unsubscribe",
    "commonNotFilled": "common.not_filled",
    "commonNotSpecified": "common.not_specified",
    "commonGoBack": "common.go_back",
    "commonUserSharedCards": "common.user_shared_cards",
    "commonUserSharedCoupon": "common.user_shared_coupon",
    "commonUserSharedOrganization": "common.user_shared_organization",
    "commonUserSharedApp": "common.user_shared_app",
    "commonUserApply": "common.apply",
    "commonReturn": "common.return",
    "commonLevel": "common.level",
    "commonExchange": "common.exchange",
    "commonCountMini": "common.count_mini",
    "commonShareMini": "common.share_mini",

    "genderMale": "gender.male",
    "genderFemale": "gender.female",
    "genderOther": "gender.other",

    "imagePickerChooseGallery": "image_picker.choose_gallery",
    "imagePickerCamera": "image_picker.camera",
    "imagePickerCancel": "image_picker.cancel",

    "notificationTitleError": "notification.title.error",
    "notificationTitleSuccess": "notification.title.success",
    "notificationTitleSystemNotification": "notification.title.system_notification",

    "permissionsTitle": "permissions.title",
    "permissionsCameraNotGranted": "permissions.camera.not_granted",
    "permissionsImagePickerNotGranted": "permissions.image_picker.not_granted",
    "permissionsLocationMessage": "permissions.location.message",

    "yupString": "yup.string",
    "yupRequired": "yup.required",
    "yupMin": "yup.min",
    "yupRegexpUrl": "yup.regexp_url",
    "yupPhone": "yup.phone",
    "yupEmail": "yup.email",

    "bottomNavigationDashboard": "bottom_navigation.business_cards",
    "bottomNavigationContacts": "bottom_navigation.contacts",
    "bottomNavigationFinance": "bottom_navigation.finance",
    "bottomNavigationCoupons": "bottom_navigation.coupons",
    "bottomNavigationBills": "bottom_navigation.bills",
    "bottomNavigationMore": "bottom_navigation.more",

    "resetPasswordHomeTitle": "reset_password.home.title",
    "resetPasswordHomeButtonReset": "reset_password.home.button_reset",
    "resetPasswordPhoneMessage": "reset_password.phone.message",
    "resetPasswordPhoneButtonRequest": "reset_password.phone.button_request",
    "resetPasswordPhoneDialogMessage": "reset_password.phone.dialog_message",
    "resetPasswordVerificationMessage": "reset_password.verification.message",
    "resetPasswordVerificationMessageRepeatCode": "reset_password.verification.message_repeat_code",
    "resetPasswordVerificationButtonRepeatCode": "reset_password.verification.button_repeat_code",
    "resetPasswordVerificationButtonSendCode": "reset_password.verification.button_send_code",

    "editPersonalBusinessCardTitle": "edit_personal_business_card.title",
    "editPersonalBusinessCardCommonData": "edit_personal_business_card.common_data",
    "editPersonalBusinessCardCommonDataMessage": "edit_personal_business_card.common_data_message",
    "editPersonalBusinessCardContactDetails": "edit_personal_business_card.contact_details",
    "editPersonalBusinessCardContactDetailsMessage": "edit_personal_business_card.contact_details_message",
    "editPersonalBusinessCardSocialNetworks": "edit_personal_business_card.social_networks",
    "editPersonalBusinessCardPersonalInformation": "edit_personal_business_card.personal_information",
    "editPersonalBusinessCardPersonalInformationMessage": "edit_personal_business_card.personal_information_message",
    "editPersonalBusinessCardBusinessCardColors": "edit_personal_business_card.business_card_colors",
    "editPersonalBusinessCardFormsActivityTitle": "edit_personal_business_card.forms.activity.title",
    "editPersonalBusinessCardFormsActivityPlaceholder": "edit_personal_business_card.forms.activity.placeholder",
    "editPersonalBusinessCardFormsPhoneTitle": "edit_personal_business_card.forms.phone.title",
    "editPersonalBusinessCardFormsPhonePlaceholder": "edit_personal_business_card.forms.phone.placeholder",
    "editPersonalBusinessCardFormsEmailTitle": "edit_personal_business_card.forms.email.title",
    "editPersonalBusinessCardFormsEmailPlaceholder": "edit_personal_business_card.forms.email.placeholder",
    "editPersonalBusinessCardFormsWebsiteTitle": "edit_personal_business_card.forms.website.title",
    "editPersonalBusinessCardFormsWebsitePlaceholder": "edit_personal_business_card.forms.website.placeholder",
    "editPersonalBusinessCardNotificationsUpdateTitle": "edit_personal_business_card.notifications.update.title",
    "editPersonalBusinessCardNotificationsUpdateMessage": "edit_personal_business_card.notifications.update.message",
    "editPersonalBusinessCardColorsPickerTitle": "edit_personal_business_card.colors_picker.title",
    "editPersonalBusinessCardColorsPickerTransparency": "edit_personal_business_card.colors_picker.transparency",
    "editPersonalBusinessCardColorsPickerSaturation": "edit_personal_business_card.colors_picker.saturation",
    "editPersonalBusinessCardColorsPickerButtonOther": "edit_personal_business_card.colors_picker.button_other",
    "editPersonalBusinessCardColorsPickerButtonSave": "edit_personal_business_card.colors_picker.button_save",
    "editPersonalBusinessCardButtonUploadImage": "edit_personal_business_card.button_upload_image",

    "languageSelectionTitle": "language_selection.title",

    "aboutAppTitle": "about_app.title",
    "aboutAppVersion": "about_app.version",
    "aboutAppButtonChangeHistory": "about_app.button_change_history",

    "businessCardAllContactTitle": "business_card_all_contact.title",

    "businessCardAllRecommendationTitle": "business_card_all_recommendation.title",

    "certificatesTitle": "certificates.title",
    "certificatesDescription": "certificates.description",
    "certificatesEmpty": "certificates.empty",
    "certificatesWhatAreCertificates": "certificates.what_are_certificates",
    "certificatesHowGet": "certificates.how_get",
    "certificatesHowUse": "certificates.how_use",

    "citySelectionTitle": "city_selection.title",
    "citySelectionCaption": "city_selection.caption",
    "citySelectionButtonSave": "city_selection.button_save",

    "companyPagesOrder": "company_pages.order",
    "companyPagesYourCashback": "company_pages.your_cashback",
    "companyPagesSuggestions": "company_pages.suggestions",
    "companyPagesOrganizationCoupons": "company_pages.organization_coupons",
    "companyPagesNotFilled": "company_pages.not_filled",
    "companyPagesYouGaveReachedMaximumCoupons": "company_pages.you_have_reached_maximum_coupons",
    "companyPagesTextLoading": "company_pages.text_loading",
    "companyPagesScheduleMessage": "company_pages.schedule_message",
    "companyPagesPromotions": "company_pages.promotions",
    "companyPagesTabInfo": "company_pages.tab_info",
    "companyPagesTabAbout": "company_pages.tab_about",
    "companyPagesTabContacts": "company_pages.tab_contacts",
    "companyPagesStaff": "company_pages.staff",
    "companyPagesClients": "company_pages.clients",
    "companyPagesBuyCouponCount": "company_pages.buy_coupon_count",
    "companyPagesCreateOrder": "company_pages.create_order",
    "companyPagesTotalCountCreateOrder": "company_pages.total_count_create_order",
    "companyPagesOperationsHistory": "company_pages.operations_history",
    "companyPagesNoFoundActiveBusinessCard": "company_pages.no_found_active_business_card",
    "companyPagesCouponAddFromUser": "company_pages.coupon_add_from_user",
    "companyPagesCreate": "company_pages.create",
    "companyPagesNext": "company_pages.next",
    "companyPagesCreateSubscription": "company_pages.create_subscription",
    "companyPagesShareCompany": "company_pages.share_company",
    "companyPagesShare": "company_pages.share",
    "companyPagesOpenMap": "company_pages.open_map",
    "companyPagesMapTitle": "company_pages.map.title",

    "contactsTitle": "contacts.title",
    "contactsNotPermission": "contacts.not_permission",
    "contactsButtonUserSystem": "contacts.button_user_system",
    "contactsMessagePermission": "contacts.message_permission",
    "contactsButtonOpenSetting": "contacts.button_open_setting",
    "contactsToInvite": "contacts.to_invite",
    "contactsOpenBusinessCard": "contacts.open_business_card",

    "couponsDisabledTitle": "coupons_disabled.title",

    "feedbackTitle": "feedback.title",

    "financeTitleLevel1": "finance.titleLevel1",
    "financeTitleLevel2": "finance.titleLevel2",
    "financeMentor": "finance.mentor",
    "financeNotMentor": "finance.not_mentor",
    "financeTitleLevel2_21": "finance.titleLevel2_21",
    "financeMyBankCards": "finance.my_bank_cards",
    "financePercent": "finance.percent",
    "financeAllHistory": "finance.all_history",
    "financeRowMarketingMessage": "finance.row_marketing_message",
    "financeRowPurchaseMessage": "finance.row_purchase_message",
    "financeRowWithdrawalMessage": "finance.row_withdrawal_message",
    "financeErrorCreateWithdrawal": "finance.error_create_withdrawal",
    "financeHistory": "finance.history",
    "financeLinkCard": "finance.link_card",
    "financeGeneralInformation": "finance.general_information",
    "financePersonalLevel": "finance.personal_level",
    "financePersonalCashback": "finance.personal_cashback",
    "financeYourCashback": "finance.your_cashback",

    "historyChangeAppTitle": "history_change_app.title",

    "informationWhenExchangingMessageLoading": "information_when_exchanging.message_loading",
    "informationWhenExchangingExchangeBusinessCards": "information_when_exchanging.exchange_business_cards",
    "informationWhenExchangingInvitationCompany": "information_when_exchanging.invitation_company",
    "informationWhenExchangingNotificationsFixExchangeMessageError": "information_when_exchanging.notifications.fix_exchange.message_error",
    "informationWhenExchangingNotificationsFixExchangeMessageSuccess": "information_when_exchanging.notifications.fix_exchange.message_success",
    "informationWhenExchangingNotificationsAcceptUserMessage": "information_when_exchanging.notifications.accept_user.message",
    "informationWhenExchangingNotificationsCancelUserMessage": "information_when_exchanging.notifications.cancel_user.message",

    "legalInformationTitle": "legal_information.title",
    "legalInformationTermsOfUse": "legal_information.terms_of_use",
    "legalInformationPrivacyPolicy": "legal_information.privacy_policy",
    "legalInformationCookiePolicy": "legal_information.cookie_policy",

    "personalBusinessCardTitle": "personal_business_card.title",

    "schedulerTitle": "scheduler.title",
    "schedulerButtonCreate": "scheduler.button_create",

    "selectedCityTitle": "selected_city.title",
    "selectedCityPlaceholder": "selected_city.placeholder",

    "componentsCouponOrganizationDisabled": "components.coupon.organization_disabled",
    "componentsCouponCouponDisabled": "components.coupon.coupon_disabled",
    "componentsCouponCouponOutStock": "components.coupon.coupon_out_stock",

    "componentsFormSendingTipsServesYou": "components.form_sending_tips.serves_you",
    "componentsFormSendingTipsDidTouLikeEverything": "components.form_sending_tips.did_you_like_everything",
    "componentsFormSendingTipsDone": "components.form_sending_tips.done",
    "componentsFormSendingTipsCheckAmount": "components.form_sending_tips.check_amount",
    "componentsFormSendingTipsEnterAmount": "components.form_sending_tips.enter_amount",
    "componentsFormSendingTipsMinimumAmount": "components.form_sending_tips.minimum_amount",
    "componentsFormSendingTipsPleaseDescribeSituation": "components.form_sending_tips.please_describe_situation",

    "componentsCutawayPartnerCompany": "components.cutaway.partner_company",
}
