#version: '3'
#
#services:
#  web:
#    build: ./
#    expose:
#      - 3000
#    ports:
#      - 3000:3000
#    volumes:
#      - ./web:/app
##  nginx:
##    image: library/nginx:latest # this will use the latest version of 1.13.x
##    ports:
##      - '80:80' # expose 80 on host and sent to 80 in container
##    depends_on:
##      - web
##    volumes:
##      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro