version: "3"
services:

  server:
    build: ./
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - 5000:5000